### ISSUE TITLE
No such file or directory: '/path/to/VQA_ODV/Group1/G1BikingToWork_ERP_3840x2160_fps23.976_qp27_12306k.yuv'

### ISSUE THREAD

**Issue by bobbyhanbin** [Archer-Tatsu/V-CNN#1]
when i enumerate the test_loader, it raises the following error:
File "C:\Users\LIGHT\Desktop\code\360VQA\dataset\dataset_VQA_ODV.py", line 75, in __call__
    ori = yuv.yuv_import(file_path, resolution, 1, frame_index)
  File "C:\Users\LIGHT\Desktop\code\360VQA\utils\yuv.py", line 16, in yuv_import
    fp = open(file_path, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/VQA_ODV/Group1/G1BikingToWork_ERP_3840x2160_fps23.976_qp27_12306k.yuv'

I download the links about this dataset, but there's no yuv files. How can I solve this problem?

**Comment by Archer-Tatsu** [comment]
1. The provided `txt` file is for example. You should modify the paths of the YUV files in practice.
2. The compressed videos are provided in the format of `mp4`. However, I converted them all to YUV for convenience. For directly using my dataset processing code, you should also convert the files to YUV, or you should implement new functions to read the mp4 files.
