### ISSUE TITLE
a question about resampling

### ISSUE THREAD

**Issue by bobbyhanbin** [Archer-Tatsu/V-CNN#3]
Hi, I notice that before the input send to the scnn, you guys make a 4k or 8k image resample into  shape with 256 x 256. and my question is why can do this, if it makes the quality of the image worst and lose some information?

**Comment by Archer-Tatsu** [comment]
The first stage of the V-CNN is designed to propose several viewports for the second stage. The output of the first stage is positional information rather than quality-related information. Therefore, the quality degradation brought by resampling does not matter.
