### ISSUE TITLE
about accuracy

### ISSUE THREAD

**Issue by bobbyhanbin** [Archer-Tatsu/V-CNN#4]
Hi, there is a question bothers me when I run this project. I found that the scroce SROCC sometimes is a large and negetive number during training, like -89.9%. Does it turns out a good performance?

**Comment by Archer-Tatsu** [comment]
Well, a large and negative SROCC means that the model gives an almost reversed order.
However, this is pretty weird. I recommend first check out the labels in the dataset, and confirm whether a smaller score or a larger score represents better quality.
